language: node_js
cache:
  directories:
    - ~/.npm
git:
  depth: 3
  script:
    - yarn build
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: main
